name: Update documentation
on:
  repository_dispatch:
    types: update

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PizziPayment/PizziAPI
          ref: Documentation
          path: doc
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm -g install redoc-cli
      - run: redoc-cli bundle doc/OpenAPI/pizzi_api.yaml
      - run: mv ./redoc-static.html ./index.html
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: git add ./index.html
      - run: git commit -m "Update documentation"
      - run: git push origin test
