name: Update documentation
on:
  repository_dispatch:

jobs:
  update-resource-server-documentation:
    if: ${{ github.event.client_payload.repo == 'resource-server' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PizziPayment/PizziResourceServer
          ref: ${{ github.event.client_payload.branch }}
          path: doc
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm -g install redoc-cli
      - run: redoc-cli bundle doc/documentation/openapi.yaml -o 'resource-server-${{ github.event.client_payload.branch }}.html'
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: git add './resource-server-${{ github.event.client_payload.branch }}.html'
      - run: git commit -m 'Update resource server (${{ github.event.client_payload.branch }}) documentation.'
      - run: git push origin main

  update-authorization-server-documentation:
    if: ${{ github.event.client_payload.repo == 'authorization-server' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PizziPayment/PizziAuthorizationServer
          ref: master
          path: doc
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install documentation dependencies
        working-directory: ./doc
        run: yarn install
      - name: Build documentation
        working-directory: ./doc
        run: yarn run builder
      - name: Move documentation
        run: mv "doc/documentation/index.html" "./authorization-server.html"
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: git add "./authorization-server.html"
      - run: git commit -m "Update authorization server documentation."
      - run: git push origin main
